### ISSUE TITLE
Train VI-Lenet model with binary VI images (GPU recommended) 

### ISSUE THREAD

**Issue by dengjinyu123** [Henry-2000/NILM_with_PLAID_dataset#1]
When I first Train VI-Lenet model with binary VI images (GPU recommended) ，I get the following problem。
Model with name plaid does not exist in current directory
I don't know how to import this .h5 file

**Comment by Henry-2000** [comment]
Hi there. For training VI-Lenet model, you first have to train the Lenet model and save it on /model directory. Did you get the .h5 file from Lenet model training?

**Comment by dengjinyu123** [comment]
> 
thanks  i know it

**Comment by dengjinyu123** [comment]
Thank you very much
