### ISSUE TITLE
V-I

### ISSUE THREAD

**Issue by WKKO** [Henry-2000/NILM_with_PLAID_dataset#3]
Hello, I'm sorry to bother you. I have been reading your article recently and have benefited a lot from it. But I have a question, how did you generate this kind of graph? I found the relevant code in your appendix, but unfortunately I cannot fully use it. If you have time, could you please help me solve this problem.
![vi](https://github.com/Henry-2000/NILM_with_PLAID_dataset/assets/102801456/299f2455-e8d8-4a25-afaf-a4e80fbc83ba)

**Comment by Henry-2000** [comment]
Hi sir, not a bother at all. Give a look at the codes on the Github page. There you will find generate_graphs.py, thats the code that I used to generate the images. You might want to edit it, regarding your graph esthetics. Let me know if u need any help understanding the code.

Best regards.

**Comment by WKKO** [comment]
> Hi sir, not a bother at all. Give a look at the codes on the Github page. There you will find generate_graphs.py, thats the code that I used to generate the images. You might want to edit it, regarding your graph esthetics. Let me know if u need any help understanding the code.
> 
> Best regards.

Thank you very much for your reply. Through your code, I have resolved this issue. Thank you very much.
